hsm/ui/Pages/AboutService.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using OCC.HSM.Model.Interfaces;
using System;

namespace OCC.HSM.UI.Pages
{
    /// <summary>
    /// The model for the summary page, supports all configured questions.
    /// </summary>
    public class AboutServiceModel : HSMPage
    {
        private IConfiguration _configuration;
                
        public string ReturnHeatPump { get; set; }

        /// <inheritdoc/>
        public AboutServiceModel(
            ILogger logger,
            IApplicationConfiguration configuration,
            IConfiguration iConfig)
            : base(logger, configuration)
        {
            if (Configuration == null)
                throw new ArgumentNullException(nameof(configuration));

            _configuration = iConfig;
        }

        #region Public Properties        

        public string EnergyRatingOfDwellings2012Url => _configuration.GetValue<string>("AppConfigSettings:EnergyRatingOfDwellings2012Url");
        public string BEISGreenhouseGasReportingUrl => _configuration.GetValue<string>("AppConfigSettings:BEISGreenhouseGasReportingUrl");

        public string PriceCapUnitRatesUrl => _configuration.GetValue<string>("AppConfigSettings:PriceCapUnitRatesUrl");

        public string BEISQuarterlyEnergyPricesUrl => _configuration.GetValue<string>("AppConfigSettings:BEISQuarterlyEnergyPricesUrl");        
        public string McsCertifiedUrl => _configuration.GetValue<string>("AppConfigSettings:McsCertifiedUrl");        
        public string OfgemPriceCapUrl => _configuration.GetValue<string>("AppConfigSettings:OfgemPriceCapUrl");
        public string BEISCostDomesticElectrificationUrl => _configuration.GetValue<string>("AppConfigSettings:BEISCostDomesticElectrificationUrl"); 
        public string ESCFeedbackFormUrl => _configuration.GetValue<string>("AppConfigSettings:ESCFeedbackFormUrl");       

        #endregion

        public IActionResult OnGet()
        {
            RemoveRedirectPageSession(HttpContext.Request.Path.Value);

            if(HttpContext.Session.GetString("HeatPump") != null)
            {
                ReturnHeatPump = HttpContext.Session.GetString("HeatPump").ToString(); 
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            return Page();
        }
    }
}

hsm/ui/Pages/EPCSummary.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OCC.HSM.Model.Entities;
using OCC.HSM.Model.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace OCC.HSM.UI.Pages
{
    /// <summary>
    /// Display a summary of the energy performance certificate.
    /// </summary>
    public class EPCSummaryModel : HSMPage
	{
		private IConfiguration _configuration;
		/// <inheritdoc/>
		public EPCSummaryModel(IApplicationConfiguration configuration, IConfiguration iConfig, ILogger logger)	
			: base(logger, configuration)
		{
			_configuration = iConfig;
		}
		public string ESCFeedbackFormUrl => _configuration.GetValue<string>("AppConfigSettings:ESCFeedbackFormUrl");

		/// <summary>
        /// Results page always needs to return to the Summary page.
        /// </summary>
        override public string ReturnPage => "PostCode";

		/// <summary>
		/// The energy performance rating as read from the state.
		/// </summary>
		public string Rating => GetStoredString(EPC_RATING_KEY);

		public string WallType => GetStoredString(WALLS_DESCRIPTION_KEY);

		public string RoofType => GetStoredString(ROOF_DESCRIPTION_KEY);

		public string WindowsType => GetStoredString(WINDOWS_DESCRIPTION_KEY);

		public string MainheatType => GetStoredString(MAINHEAT_DESCRIPTION_KEY);

		public string FloorArea => GetStoredString(FLOOR_AREA_KEY);

		public string PropertyType => GetStoredString(PROPERTY_TYPE_KEY);
			
		/// <summary>
		/// The stored value for date the rating was lodged the as derived from 
		/// the certificate.
		/// </summary>
		public string RatingDate
		{
			get
			{
				string str = GetStoredString(EPC_RATING_DATE_KEY);

				if (!string.IsNullOrEmpty(str))
				{
					if (DateTime.TryParse(str, out DateTime date))
					{
						return $"{date:MMMM yyyy}";
					}
				}
				return null;
			}
		}

		public async Task<IActionResult> OnGet()
        {
			bool isEpcPresent = Convert.ToBoolean(HttpContext.Session.GetString("IsEpcPresent"));
			if(!isEpcPresent)
            {
				return RedirectToPage("/Postcode");
            }

			RemoveRedirectPageSession(HttpContext.Request.Path.Value);

			//After clicking Continue Without EPC button, all the EPC answers will be cleared. If the user then clicks the browser's back button 
			//they shouldn't return to this page, because it won't contain any EPC data, for this reaseon redirecting to the Postcode page is more meaningfull
			if (string.IsNullOrEmpty(Rating) &&
				string.IsNullOrEmpty(RatingDate) &&
				string.IsNullOrEmpty(WallType) &&
				string.IsNullOrEmpty(RoofType) &&
				string.IsNullOrEmpty(WindowsType) &&
				string.IsNullOrEmpty(MainheatType) &&
				string.IsNullOrEmpty(FloorArea) &&
				string.IsNullOrEmpty(PropertyType))
            {
				return RedirectToPage("Postcode");
			}
			return Page();			
		}
		
		/// <summary>
		/// Called when the form is posted back by the Continue button click.  Sets the
		/// "skip 
		/// </summary>
		/// <returns>Redirects to the question page</returns>
		public IActionResult OnPost()
		{
			//After clicking Continue Without EPC button, all the EPC answers will be cleared. If the user then clicks the browser's back button 
			//they shouldn't return to this page, because it won't contain any EPC data, for this reaseon redirecting to the Postcode page is more meaningfull
			if (string.IsNullOrEmpty(Rating) &&
				string.IsNullOrEmpty(RatingDate) &&
				string.IsNullOrEmpty(WallType) &&
				string.IsNullOrEmpty(RoofType) &&
				string.IsNullOrEmpty(WindowsType) &&
				string.IsNullOrEmpty(MainheatType) &&
				string.IsNullOrEmpty(FloorArea) &&
				string.IsNullOrEmpty(PropertyType))
			{
				return RedirectToPage("Postcode");
			}

			RemoveRedirectPageSession(HttpContext.Request.Path.Value);
			return Page();
		}

		public IActionResult OnPostContinueWithEPC()
        {			
			HttpContext.Session.SetString("ContinueWithEpc", "true");
			return RedirectToPage("QuestionIntro");
		}

		public IActionResult OnPostContinueWithoutEPC()
        {
			RemoveRedirectPageSession(HttpContext.Request.Path.Value);

			HttpContext.Session.SetString("ContinueWithEpc", "false");
			HttpContext.Session.SetString("IsEpcPresent", "false");
			SetSkipAnsweredQuestions(false);
			ClearAnswers();
			return RedirectToPage("QuestionIntro");
		}
		
		/// <summary>
		/// Gets all the answered questions for displaying on the page.
		/// </summary>
		/// <returns>An enumerable of strings each prefixed with the breadcrumb text (to 
		/// keep the prompt short) followed by the answer text.</returns>
		public IEnumerable<string> GetAnswers()
		{
			foreach(Question question in Configuration.Questions) {
				string answerKey = GetStoredString(question.Key);

				if(!String.IsNullOrEmpty(answerKey)) {
					AnswerChoice answer = question.AnswerChoices.FirstOrDefault(ans => ans.Key == answerKey);

					if(answer != null)
						yield return $"{question.BreadcrumbText}: {answer.Text}";
				}
			}
		}
	}
}

hsm/ui/Pages/PostCode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using OCC.HSM.Model.Entities;
using OCC.HSM.Model.Interfaces;
using OCC.HSM.UI.Pages.Enums;
using static System.Net.WebUtility;

using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;

namespace OCC.HSM.UI.Pages
{
	/// <summary>
	/// The model behind the post code page.  This page takes the user through the process
	/// of entering a postcode, selecting one of the matching addresses for which a
	/// certificate is available or allowing the user to continue without information
	/// taken from a certificate.  If a certificate is found this page will pass on the
	/// information to the EPC summary page, if no certificate the site will navigate
	/// directly to the first question.
	/// </summary>	
	public class PostCodeModel : HSMPage
	{
		private IConfiguration _configuration;
		/// <summary>
		/// The connection to the energy performance certificate source.
		/// </summary>
		private IEPCService EPC { get; }

		/// <summary>
		/// A regular expression to validate postcodes before submitting to the EPC, this
		/// pattern seems adequate for addresses in England.
		/// </summary>
		private readonly Regex rePostcode = new Regex(
			@"^([A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}|GIR ?0A{2})$", RegexOptions.Compiled);

		/// <summary>
		/// Used to extract the leading digits from an address string.
		/// </summary>
		private static readonly Regex reDoorNumber_ = new Regex(@"^\d+", RegexOptions.Compiled);

		/// <summary>
		/// Bound to the postcode input field on the page.
		/// </summary>
		[BindProperty]
		public string PostcodeText { get; set; }

		/// <summary>
		/// Bound to the text selected in the drop-down list of addresses.
		/// </summary>
		[BindProperty]
		public string AddressText { get; set; }

		/// <summary>
		/// The list of addresses in <see cref="SelectList"/> format for the drop-down on
		/// the page to read from.
		/// </summary>
		public SelectList Addresses { get; private set; }

		/// <summary>
		/// This is set to give the user additional information for cases when the postcode
		/// is either invalid or there are no certificates available. When this is set the
		/// address list is not shown.
		/// </summary>
		public string Message { get; private set; }

		/// <summary>
		/// The EPC response code.
		/// </summary>
		public EPCResponse EPCResponseCode { get; set; } = EPCResponse.CertificateFound;

        /// <summary>
        /// Not all messages can be an error statement. This property is set to distinguish when the entered postcode is invalid or empty.
        /// </summary>
        public bool IsError { get; set; }

		/// <summary>
        /// PostCode is now the landing page
        /// </summary>
        override public string ReturnPage => "";

		public string ESCFeedbackFormUrl => _configuration.GetValue<string>("AppConfigSettings:ESCFeedbackFormUrl");

		/// <summary>
		/// Create a new instance with the service and logger.
		/// </summary>
		public PostCodeModel(IEPCService epcService, ILogger logger,
			IApplicationConfiguration configuration,
			IConfiguration iConfig) : base(logger, configuration)
		{
			EPC = epcService;
			_configuration = iConfig;
		}

		/// <summary>
		/// Clear the existing answers.
		/// </summary>
		public async Task<IActionResult> OnGet()
		{          
            RemoveRedirectPageSession("/Postcode");

			if (!string.IsNullOrEmpty(HttpContext.Session.GetString("postcode")))
			{
				PostcodeText = HttpContext.Session.GetString("postcode");
				
				await LoadPostcodeAddresses();
			}

			ClearAnswers();			

			return Page();
		}

        /// <summary>
        /// The postcode should have been submitted, use the EPC service to look up using
        /// the postcode and populate the list of addresses.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostPostcode()
		{
			Message = string.Empty;

			if (string.IsNullOrEmpty(PostcodeText))
            {
				IsError = true;
				Message = Helpers.Extensions.GetDescription(EPCResponse.PostCodeIsNullOrWhiteSpace);
				return Page();
			}
			
			HttpContext.Session.SetString("postcode", PostcodeText);

			ClearAnswers();

			await LoadPostcodeAddresses();

            if (EPCResponseCode == EPCResponse.NoCertificateFound || EPCResponseCode == EPCResponse.EPCServiceCurrentlyNotAvailable)
            {
                return RedirectToPage("EPCNotFound");
            }
            			
			return RedirectToPage("Postcode");						
		}

		/// <summary>
		/// This method gets called when the Change button is clicked.
		/// </summary>
		/// <returns></returns>
		public async Task<IActionResult> OnPostChangePostcode()
        {
			PostcodeText = string.Empty;
			HttpContext.Session.SetString("postcode", string.Empty);
			return RedirectToPage("Postcode");
		}

		/// <summary>
		/// Called when the user has submitted their address from the selection of addresses.
		/// If the user clicks the button without selecting an address simply go back, not
		/// attempting to add additional prompts to select an address.
		/// </summary>
		/// <returns>A redirect to the next page, which may be this one.</returns>
		public async Task<IActionResult> OnPostSelectAddress()
		{
			PostcodeText = HttpContext.Session.GetString("postcode");
			HttpContext.Session.Remove("ContinueWithEpc");
			try {
				if(string.IsNullOrEmpty(AddressText) || AddressText.Equals("found")) {
					IsError = true;
					Message = Helpers.Extensions.GetDescription(EPCResponse.AddressIsNullOrWhiteSpace); 
					await TryGetAddressList().ConfigureAwait(true);
				} else {
					IDictionary<string, string> cert
						= await EPC.CertificateFromAddress(AddressText, PostcodeText).ConfigureAwait(true);

					if(cert == null)
                    {
						HttpContext.Session.SetString("IsEpcPresent", "false");
						return RedirectToPage("EPCNotFound");
					}

					HttpContext.Session.SetString("IsEpcPresent", "true");

					int answeredQuestions = AnswersFromCertificate(cert);

					foreach((string key, string epcKey) in STORED_EPC_VALUES) {
						StoreString(key, GetEPCValue(epcKey, cert));
					}

					return RedirectToPage(answeredQuestions == 0
						? "Question"
						: "EPCSummary");
				}
			} catch(Exception ex) {
				Message = LogException(ex);
			}
			
			HttpContext.Session.SetString("IsEpcPresent", "false");
			return Page();			
		}

		/// <summary>
		/// Gets called when the user clicks the "Continue without postcode" link.
		/// </summary>
		/// <returns>Redirects to the first question page</returns>
		public IActionResult OnPostWithoutEPCData()
		{
			HttpContext.Session.SetString("ContinueWithEpc", "false");
			HttpContext.Session.SetString("IsEpcPresent", "false");
			ClearValue(POSTCODE_KEY);
			ClearAnswers();
			return RedirectToPage("QuestionIntro");			
		}

		/// <summary>
		/// Attempt to find the answers to questions from the energy performance certificate
		/// using the mappings built into the answer choices.
		/// </summary>
		/// <param name="certificate">The certificate in the form of a dictionary mapping
		/// key => value</param>
		/// <returns>The number of answers obtained from the certificate</returns>
		private int AnswersFromCertificate(IDictionary<string, string> certificate)
		{
			int answeredQuestions = 0;

			if(certificate != null && Configuration.Questions is IQuestionCollection questions) {
				foreach(Question question in questions) {
					foreach(var answer in question.AnswerChoices) {
						if(answer.Matches(certificate) && !question.Key.Equals("housesizeoption2")) {
							StoreString(question.Key, answer.Key);
							++answeredQuestions;

							//Skip question according to the result
							//If housesizeoption1 has been matched from the EPC, then skip the Number of bedrooms question(mark it as answered, but don't display it in the Summary page as it wasn't answered by the user)
							if (question.Key.Equals("housesizeoption1"))
							{
								StoreString("housesizeoption2", "housesizeoption2-1");							

								SetQuestionHidden("housesizeoption2", true, true);
								++answeredQuestions;
							}
							break;
						}
					}
				}
			}
			return answeredQuestions;
		}

		/// <summary>
		/// A helper method to call the EPC service and populate the <see cref="Addresses"/>
		/// member and also the <see cref="Message"/> member when appropriate.
		/// </summary>
		private async Task TryGetAddressList()
		{
			if(!string.IsNullOrWhiteSpace(PostcodeText)) {
				string postcode = PostcodeText.Trim().ToUpperInvariant();
				if(rePostcode.Match(postcode).Success) {
					PostcodeText = postcode;
					Addresses = null;

					try {
						Task setCountry = SetCountryFromPostcode(PostcodeText);
						Task<IList<string>> getAddresses = EPC.AddressesFromPostcode(PostcodeText);

						await Task.WhenAll(setCountry, getAddresses).ConfigureAwait(true);

						var addrList = getAddresses.Result;

						if(addrList.Count > 0) {
							List<string> lst = addrList.ToList();
							lst.Sort((a, b) => GetDoorNumber(a) - GetDoorNumber(b));

							Addresses = new SelectList(lst);
						} else {

							EPCResponseCode = EPCResponse.NoCertificateFound;
							Message = Helpers.Extensions.GetDescription(EPCResponseCode);
						}
					} catch(Exception ex) {
						Logger.Exception(ex);
						EPCResponseCode = EPCResponse.EPCServiceCurrentlyNotAvailable;
						Message = Helpers.Extensions.GetDescription(EPCResponseCode);							
					}
				} else {
					IsError = true;
					EPCResponseCode = EPCResponse.InvalidPostCode;
					Message = Helpers.Extensions.GetDescription(EPCResponseCode);
				}
			} else {
				IsError = true;

hsm/ui/Pages/EPCSummary.cshtml
@page
@model OCC.HSM.UI.Pages.EPCSummaryModel
@{
    ViewData["Title"] = "EPCSummary";
    Layout = "~/Pages/Shared/_mainLayout.cshtml";

    string epc_image = String.Empty;
    string energyRating = "?";
    string ratingDate = Model.RatingDate;

    if (!String.IsNullOrEmpty(Model.Rating) && Model.Rating.Length == 1)
    {
        epc_image = $"mini-epc-{Model.Rating.ToLower()}.png";
        energyRating = Model.Rating.ToUpperInvariant();
    }
}

<form method="post">
    <div class="hsm-EPCSummary-page">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds-from-desktop">
                <section class="hsm-EPCSummary-page-section hsm-EPCSummary-page-section-overview govuk-!-margin-bottom-6">
                    <h1 class="govuk-heading-xl govuk-!-margin-bottom-5 hsm-heading-1">Your EPC summary</h1>
                    <p class="govuk-body govuk-!-margin-bottom-3">Based on your address we found the latest EPC certificate for your home which means that some of the questions ahead can be answered for you.</p>
                    <p class="govuk-body govuk-!-margin-bottom-3">An Energy Performance Certificate (EPC) was produced for your home in @ratingDate.</p>
                    <p class="govuk-body govuk-!-margin-bottom-5">Your home was given an energy rating of @energyRating. Most homes appear around grade D.</p>
                    <dl class="govuk-summary-list govuk-!-margin-bottom-8">
                        <div class="govuk-summary-list__row">
                            <dt class="govuk-summary-list__key">
                                Property type
                            </dt>
                            <dd class="govuk-summary-list__value">
                                @Model.PropertyType
                            </dd>
                        </div>
                        <div class="govuk-summary-list__row">
                            <dt class="govuk-summary-list__key">
                                Total floor area
                            </dt>
                            <dd class="govuk-summary-list__value">
                                @Model.FloorArea square metres
                            </dd>
                        </div>
                    </dl>
                </section>

                <section class="hsm-EPCSummary-page-section hsm-EPCSummary-page-section-features govuk-!-margin-bottom-6">
                    <table class="govuk-table">
                        <caption class="govuk-table__caption govuk-table__caption--l">Your property’s features</caption>
                        <thead class="govuk-table__head">
                            <tr class="govuk-table__row">
                                <th scope="col" class="govuk-table__header">Feature</th>
                                <th scope="col" class="govuk-table__header">Description</th>
                            </tr>
                        </thead>
                        <tbody class="govuk-table__body">
                            <tr class="govuk-table__row">
                                <th scope="row" class="govuk-table__header">Wall</th>
                                <td class="govuk-table__cell">@Model.WallType</td>
                            </tr>
                            <tr class="govuk-table__row">
                                <th scope="row" class="govuk-table__header">Roof</th>
                                <td class="govuk-table__cell">@Model.RoofType</td>
                            </tr>
                            <tr class="govuk-table__row">
                                <th scope="row" class="govuk-table__header">Window</th>
                                <td class="govuk-table__cell">@Model.WindowsType</td>
                            </tr>
                            <tr class="govuk-table__row">
                                <th scope="row" class="govuk-table__header">Main heating</th>
                                <td class="govuk-table__cell">@Model.MainheatType</td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="govuk-inset-text">
                        You will be able to review and edit this information prior to obtaining your results. 
                    </div>
                    <input type="submit" asp-page-handler="ContinueWithEPC" value="Continue" class="govuk-button govuk-!-display-block" data-module="govuk-button">

                    <p class="govuk-body govuk-!-margin-bottom-3">If this information is incorrect then 
                    <input type="submit" asp-page-handler="ContinueWithoutEPC" value="Continue without Energy Performance Certificate (EPC)" class="govuk-body govuk-link hsm-form-link hsm-input-epc-large" role="link"/>
                    <input type="submit" asp-page-handler="ContinueWithoutEPC" value="Continue without EPC" class="govuk-body govuk-link hsm-form-link hsm-input-epc-small" role="link" />
                    </p>
                </section>
            </div>
        </div>
    </div>
</form>

hsm/ui/Pages/PageNotFound.cshtml
@page
@model OCC.HSM.UI.Pages.PageNotFoundModel
@{
	ViewData["Title"] = "Page not found – Check if a Heat Pump is Suitable for Your Home – GOV.UK";
    Layout = "~/Pages/Shared/_mainLayout.cshtml";
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Page not found</h1>
        <p class="govuk-body">If you typed the web address, check it is correct.</p>
        <p class="govuk-body">If you pasted the web address, check you copied the entire address.</p>
    </div>
</div>

hsm/ui/Pages/PostCode.cshtml
@page "{handler?}"
@model OCC.HSM.UI.Pages.PostCodeModel
@{
    ViewData["Title"] = "Postcode";
    Layout = "~/Pages/Shared/_altLayoutHome.cshtml";
}

<div class="hsm-post-code-page">
    <div class="govuk-grid-row govuk-!-margin-bottom-5">
        <div class="govuk-grid-column-two-thirds-from-desktop">
            @if (Model.IsError)
            {
                <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="govuk-error-summary">
                    <h2 class="govuk-error-summary__title" id="error-summary-title">
                        There is a problem
                    </h2>
                    <div class="govuk-error-summary__body">
                        <ul class="govuk-list govuk-error-summary__list">
                            <li>
                                <a href="@(Model.Addresses == null ? "#address-postcode" : "#select-address")">@Model.Message</a>
                            </li>
                        </ul>
                    </div>
                </div>
            }
            <section class="hsm-post-code-page-section hsm-post-code-page-section-info govuk-!-margin-bottom-6">
                <h1 class="govuk-heading-xl govuk-!-margin-bottom-5 hsm-heading-1">Enter your postcode to find information about your home</h1>
                <p class="govuk-body govuk-!-margin-bottom-3 hsm-start-page-section__paragraph">Telling us your postcode and address lets us find your Energy Performance Certificate (EPC) which contains information about the energy efficiency of your home. This information can then be used to auto-populate answers to some of our questions about your home. </p>
                <ul class="govuk-list govuk-list--bullet govuk-!-margin-bottom-5">
					<li>If an EPC is available, this information can be used to auto-populate some of your answers. </li>
					<li>If an EPC is not available, you can continue without this information and manually answer the questions about your home.</li>
				</ul>
            </section>

            <form method="post" novalidate>
                @if (Model.Addresses == null)
                {
                    <div class="govuk-form-group govuk-!-margin-bottom-3 @(Model.IsError && !string.IsNullOrEmpty(Model.Message) ? "govuk-form-group--error" : "")">
                        <label class="govuk-label govuk-!-font-size-27 govuk-!-font-weight-bold" for="address-postcode">
                            Postcode
                        </label>
                        @if (Model.IsError && !String.IsNullOrEmpty(Model.Message))
                        {
                            <p id="address-postcode-error" class="govuk-error-message">
                                <span class="govuk-visually-hidden">Error:</span> @Model.Message
                            </p>
                        }
                        <input type="text" asp-for="PostcodeText" value="@Model.PostcodeText" id="address-postcode" class="govuk-input hsm-input--postcode" autocomplete="postal-code">

                    </div>

                    <button class="govuk-button" data-module="govuk-button" asp-page-handler="Postcode">Find my address</button>
                    <p class="govuk-body hsm-margin-bottom-0">
                        <input type="submit" value="Continue without Energy Performance Certificate (EPC)" asp-page-handler="WithoutEPCData" class="govuk-body govuk-link hsm-form-link hsm-input-epc-large" role="link"/>
                    </p>
                    <p class="govuk-body hsm-margin-bottom-0">
                        <input type="submit" value="Continue without EPC" asp-page-handler="WithoutEPCData" class="govuk-body govuk-link hsm-form-link hsm-input-epc-small" role="link"/>
                    </p>
                }
                else if (Model.Addresses != null && Model.Addresses.Count() > 0)
                {
                    <div class="govuk-form-group govuk-!-margin-bottom-3">
                        <h2 class="govuk-body govuk-!-font-size-24 govuk-!-font-weight-bold hsm-margin-bottom-1">
                            Postcode
                        </h2>
                        <span class="govuk-body govuk-!-font-weight-bold govuk-!-margin-right-3 hsm-margin-bottom-0">@Model.PostcodeText</span>
                        <input type="submit" value="Change postcode" asp-page-handler="ChangePostcode" class="govuk-body govuk-link govuk-link--no-visited-state hsm-form-link hsm-margin-bottom-0" role="link"/>
                    </div>

                    <div class="govuk-form-group govuk-!-margin-bottom-5 @(string.IsNullOrEmpty(Model.Message) ? "" : "govuk-form-group--error")">
                        <p class="govuk-body govuk-!-margin-bottom-3 hsm-start-page-section__paragraph">We found Energy Performance Certificates (EPCs) for the following properties:  </p>
                        <label class="govuk-label govuk-visually-hidden" for="select-address">
                            Select an address
                        </label>
                        @if (!String.IsNullOrEmpty(Model.Message))
                        {
                            <p id="address-postcode-error" class="govuk-error-message">
                                <span class="govuk-visually-hidden">Error:</span> @Model.Message
                            </p>
                        }
                        <select asp-for="AddressText" asp-items="@Model.Addresses" class="govuk-select govuk-!-width-two-thirds" id="select-address">
                            <option value="found" selected>@Model.Addresses.Count() addresses found</option>
                        </select>
                    </div>

                    <button asp-page-handler="SelectAddress" class="govuk-button govuk-!-display-block" data-module="govuk-button">Continue</button>

                    <p class="govuk-body hsm-margin-bottom-0">
                        If your address is not listed, please
                        <input type="submit" value="Continue without Energy Performance Certificate (EPC)" asp-page-handler="WithoutEPCData" class="govuk-body govuk-link hsm-form-link hsm-input-epc-large" role="link"/>
                        <input type="submit" value="Continue without EPC" asp-page-handler="WithoutEPCData" class="govuk-body govuk-link hsm-form-link hsm-input-epc-small" role="link"/>
                    </p>
                }
            </form>
        </div>
    </div>
</div>